name: Lint # name of the action (displayed in the github interface)
on: [pull_request]
env: # environment variables (available in any part of the action)
  NODE_VERSION: 20
jobs:
  linting:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest

    steps:
       - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Commit message Linting
      - run: npm install -g @commitlint/{cli,config-conventional}
      - run: commitlint --from ${{ github.event.pull_request.base.sha }}
                        --to ${{ github.event.pull_request.head.sha }}
                        --verbose

      - name: Code Linting
        run: ng lint

